Allow ion diffusion
jaxleyverse/jaxley pull request #438
Opened 2024-10-03 13:39 UTC by michaeldeistler

```python
comp = jx.Compartment()
branch = jx.Branch(comp, nseg=4)
cell = jx.Cell(branch, parents=[-1, 0, 0])

cell.insert(CaHVA())
cell.insert(CaNernstReversal())
cell.insert(CaPump())

cell.diffuse("CaCon_i")
cell.set("axial_resistivity_CaCon_i", 0.001)
cell.make_trainable("axial_resistivity_CaCon_i")
```

2025-02-04 14:46 UTC, jnsbck commented
Cool that you are working on this again. Lemme know if you need prelim ipt :)

2025-02-04 14:47 UTC, michaeldeistler commented
Yes let's discuss tmr!

2025-02-05 09:25 UTC, huangziwei commented
I'd suggest baking the `derivative()` method and the channel solver extension into `jaxley/channels/channel.py` (or should we abstract it one level higher, as these are also used by synapses?).

2025-02-21 08:43 UTC, michaeldeistler commented
/update_regression_baselines

2025-02-21 08:44 UTC, michaeldeistler commented
/test_regression

2025-02-21 12:38 UTC, michaeldeistler commented
/test_regression

2025-02-24 13:40 UTC, jnsbck requested changes
This is really awesome! I really like the `.diffuse()` API having a similar feel to `record()`, `stimulate()` etc. Also amazing work on all of the nitty gritty! I went through it all and left a bunch of comments here and there. Once addressed, this can be merged from my side.

One thought I had while going through this:
I am not a big fan of all the `if has_diffusion` statements and would love to think up some better abstraction level to handle this in the future. It would make sense to do this when finalizing the `Mechanism` API  and how to merge the backend for synapses / channels / and pumps efficiently. 

Let me know if you need another round of feedback after making the changes. Otherwise good to merge from my side. Should you make a release, see the updated [Release Workflow](https://github.com/jaxleyverse/jaxley/wiki/Release-workflow).

2025-02-24 13:40 UTC, jnsbck commented on jaxley/modules/base.py
> +        """Set channels to show only those in view."""
...set pumps...

2025-02-24 13:40 UTC, jnsbck commented on tests/jaxley_vs_neuron/test_branch.py
> +    branch = jx.Branch(comp, ncomp=2)
could also use fixture `branch = SimpleBranch(2)`

2025-02-24 13:40 UTC, jnsbck commented on tests/jaxley_vs_neuron/test_branch.py
> +@pytest.mark.skip
could also be marked with xfail, which I think would make more sense

2025-02-24 13:40 UTC, jnsbck commented on tests/jaxley_vs_neuron/test_branch.py
> +    whether diffusion is activated or not_. This make no sense to me (Michael), so I
use github handle

2025-02-24 13:40 UTC, jnsbck commented on tests/jaxley_vs_neuron/test_branch.py
> +    once_) even for the voltage equations.
link this in known differences issues #140

2025-02-24 13:40 UTC, jnsbck commented on tests/jaxley_vs_neuron/test_cell.py
> +    cell = jx.Cell(branch, parents=[-1, 0, 0])
`cell = SimpleCell(3,2)`

2025-02-24 13:40 UTC, jnsbck commented on tests/jaxley_vs_neuron/test_cell.py
> +    # of compartments are not the same (as is the case here).
We could also make this a test and xfail it if we want

2025-02-24 13:40 UTC, jnsbck commented on tests/test_ion_diffusion_and_pumps.py
> +class NaPump(Pump):
Maybe call it `TestPump`, like `TestSynapse`

2025-02-24 13:40 UTC, jnsbck commented on tests/test_ion_diffusion_and_pumps.py
> +    def init_state(
Can we test the init method somewhere as well, even if nonesensical?

2025-02-24 13:40 UTC, jnsbck commented on tests/test_ion_diffusion_and_pumps.py
> +    cell = jx.Cell(branch, parents=[-1, 0])
`cell = SimpleCell(2,2)`

2025-02-24 13:40 UTC, jnsbck commented on tests/test_ion_diffusion_and_pumps.py
> +# This file is part of Jaxley, a differentiable neuroscience simulator. Jaxley is
Having a regression test case for pumps / diffusion would be great I think.

2025-02-24 13:40 UTC, jnsbck commented on tests/test_ion_diffusion_and_pumps.py
> +# This file is part of Jaxley, a differentiable neuroscience simulator. Jaxley is
A test that asserts against some hardcoded results, i.e. like in `jaxley_identical`, would also be a good tripwire for the future I think.

2025-02-24 13:40 UTC, jnsbck commented on tests/test_ion_diffusion_and_pumps.py
> +# This file is part of Jaxley, a differentiable neuroscience simulator. Jaxley is
As talked about, storing the voltages from the NEURON test somewhere, would forgoe the need to compile the channel models and we could get rid of the `additional_neuron_tests` flag and related alltogether.

2025-02-24 13:40 UTC, jnsbck commented on jaxley/modules/base.py
> +    def diffuse(self, state: str):
We might want to add a method `delete_pumps` or the like. Also fine with adding it later and opening an issue for now.

2025-02-24 14:48 UTC, michaeldeistler commented on jaxley/channels/__init__.py
> +from jaxley.channels.nernstreversal import CaNernstReversal
I will just make it a Pump. Since it has an empty `compute_current` it does not matter.

2025-02-24 14:57 UTC, michaeldeistler commented on jaxley/pumps/ca_pump.py
> +        self.current_name = "i_CaPump"
hm not sure. The `_i` signals "intracellular". It is the same in NEURON. I think I will keep it as it is for now, but I do like `"[Ca]_i"` instead of `CaCon_i`.

2025-02-24 14:58 UTC, michaeldeistler commented on jaxley/pumps/ca_pump.py
> +            f"{self._name}_minCai": 1e-4,  # Minimum intracell. ca concentration in mM.
will change it here.

2025-02-24 15:00 UTC, michaeldeistler commented on jaxley/pumps/faraday_electrolysis.py
> +def convert_current_to_molarity_change(
hmm difficult. I see the point for moving it, but I also like that this lives right here in the `Pump` which will make it easier for users (if they check out the code) to see what's happening...I think I will leave it.

2025-02-24 15:05 UTC, michaeldeistler commented on jaxley/utils/cell_utils.py
> +    g_axial = rad1 * rad2^2 / (l1 * r_a1 * rad2^2 + l2 * r_a2 * rad1^2) / l1
yes they are the same, will change it

2025-02-24 15:38 UTC, michaeldeistler commented on tests/jaxley_vs_neuron/test_cell.py
> +    # of compartments are not the same (as is the case here).
no because it will cause a segmentation fault later on :D

2025-02-24 15:48 UTC, michaeldeistler commented on jaxley/modules/base.py
> +                )
I don't think I understand the arguments ofr `step_pumps`. It would be almost an exact copy of `step_channels`. I don't think we need both.

2025-02-25 07:29 UTC, michaeldeistler commented on jaxley/modules/base.py
> +    def diffuse(self, state: str):
I agree. I changed `.delete_channels()` to `.delete()` and made it also handle `Pump`s. I also added `.delete_diffusion()`.

2025-02-25 07:41 UTC, michaeldeistler commented on jaxley/modules/base.py
> +        self.pumps: List[Pump] = []
I followed up on this at #592

2025-02-25 16:49 UTC, merged